const characters=["マリオ", "ドンキーコング", "リンク", "サムス/ダークサムス", "ヨッシー", "カービィ", "フォックス", "ピカチュウ", "ルイージ", "ネス", "キャプテン・ファルコン", "プリン", "ピーチ/デイジー", "クッパ", "アイスクライマー", "シーク", "ゼルダ", "ドクターマリオ", "ピチュー", "ファルコ", "マルス", "ルキナ", "こどもリンク", "ガノンドロフ", "ミュウツー", "ロイ", "クロム", "Mr.ゲーム&ウォッチ", "メタナイト", "ピット/ブラックピット", "ゼロスーツサムス", "ワリオ", "スネーク", "アイク", "ポケモントレーナー", "ディディーコング", "リュカ", "ソニック", "デデデ", "ピクミン&オリマー", "ルカリオ", "ロボット", "トゥーンリンク", "ウルフ", "むらびと", "ロックマン", "Wii Fit トレーナー", "ロゼッタ&チコ", "リトル・マック", "ゲッコウガ", "Mii格闘タイプ", "Mii剣術タイプ", "Mii射撃タイプ", "パルテナ", "パックマン", "ルフレ", "シュルク", "クッパJr.", "ダックハント", "リュウ", "ケン", "クラウド", "カムイ", "ベヨネッタ", "インクリング", "リドリー", "シモン/リヒター", "キングクルール", "しずえ", "ガオガエン", "パックンフラワー", "ジョーカー", "勇者", "バンジョー&カズーイ", "テリー", "ベレト/ベレス", "ミェンミェン", "スティーブ", "セフィロス", "ホムラ/ヒカリ", "カズヤ", "ソラ"];
const charIconMap={"マリオ": "マリオ.png", "ドンキーコング": "ドンキーコング.png", "リンク": "リンク.png", "サムス/ダークサムス": "サムス_ダークサムス.png", "ヨッシー": "ヨッシー.png", "カービィ": "カービィ.png", "フォックス": "フォックス.png", "ピカチュウ": "ピカチュウ.png", "ルイージ": "ルイージ.png", "ネス": "ネス.png", "キャプテン・ファルコン": "キャプテン_ファルコン.png", "プリン": "プリン.png", "ピーチ/デイジー": "ピーチ_デイジー.png", "クッパ": "クッパ.png", "アイスクライマー": "アイスクライマー.png", "シーク": "シーク.png", "ゼルダ": "ゼルダ.png", "ドクターマリオ": "ドクターマリオ.png", "ピチュー": "ピチュー.png", "ファルコ": "ファルコ.png", "マルス": "マルス.png", "ルキナ": "ルキナ.png", "こどもリンク": "こどもリンク.png", "ガノンドロフ": "ガノンドロフ.png", "ミュウツー": "ミュウツー.png", "ロイ": "ロイ.png", "クロム": "クロム.png", "Mr.ゲーム&ウォッチ": "Mr_ゲーム_ウォッチ.png", "メタナイト": "メタナイト.png", "ピット/ブラックピット": "ピット_ブラックピット.png", "ゼロスーツサムス": "ゼロスーツサムス.png", "ワリオ": "ワリオ.png", "スネーク": "スネーク.png", "アイク": "アイク.png", "ポケモントレーナー": "ポケモントレーナー.png", "ディディーコング": "ディディーコング.png", "リュカ": "リュカ.png", "ソニック": "ソニック.png", "デデデ": "デデデ.png", "ピクミン&オリマー": "ピクミン_オリマー.png", "ルカリオ": "ルカリオ.png", "ロボット": "ロボット.png", "トゥーンリンク": "トゥーンリンク.png", "ウルフ": "ウルフ.png", "むらびと": "むらびと.png", "ロックマン": "ロックマン.png", "Wii Fit トレーナー": "Wii_Fit_トレーナー.png", "ロゼッタ&チコ": "ロゼッタ_チコ.png", "リトル・マック": "リトル_マック.png", "ゲッコウガ": "ゲッコウガ.png", "Mii格闘タイプ": "Mii格闘タイプ.png", "Mii剣術タイプ": "Mii剣術タイプ.png", "Mii射撃タイプ": "Mii射撃タイプ.png", "パルテナ": "パルテナ.png", "パックマン": "パックマン.png", "ルフレ": "ルフレ.png", "シュルク": "シュルク.png", "クッパJr.": "クッパJr_.png", "ダックハント": "ダックハント.png", "リュウ": "リュウ.png", "ケン": "ケン.png", "クラウド": "クラウド.png", "カムイ": "カムイ.png", "ベヨネッタ": "ベヨネッタ.png", "インクリング": "インクリング.png", "リドリー": "リドリー.png", "シモン/リヒター": "シモン_リヒター.png", "キングクルール": "キングクルール.png", "しずえ": "しずえ.png", "ガオガエン": "ガオガエン.png", "パックンフラワー": "パックンフラワー.png", "ジョーカー": "ジョーカー.png", "勇者": "勇者.png", "バンジョー&カズーイ": "バンジョー_カズーイ.png", "テリー": "テリー.png", "ベレト/ベレス": "ベレト_ベレス.png", "ミェンミェン": "ミェンミェン.png", "スティーブ": "スティーブ.png", "セフィロス": "セフィロス.png", "ホムラ/ヒカリ": "ホムラ_ヒカリ.png", "カズヤ": "カズヤ.png", "ソラ": "ソラ.png"};
const stages=[{name:"戦場",short:"戦"},{name:"小戦場",short:"小"},{name:"終点",short:"終"},{name:"ポケ2",short:"ポ"},{name:"ホロバス",short:"ホ"},{name:"村町",short:"村"},{name:"スマ村",short:"ス"}];
const defaultSections=["立ち回り","着地狩り","崖","復帰","撃墜","コンボ"];
let selectedMy=null,selectedOpponent=null,editingSectionIndex=null;
const $=id=>document.getElementById(id);const screens=["homeScreen","registerScreen","opponentScreen","matchupScreen"].map(id=>$(id));
function show(id){screens.forEach(s=>s.classList.remove("active"));$(id).classList.add("active");window.scrollTo(0,0);}
function getStore(){return JSON.parse(localStorage.getItem("smashMemoV3")||"{}");}function setStore(d){localStorage.setItem("smashMemoV3",JSON.stringify(d));}
function initStore(){const d=getStore();if(!d.registered)d.registered=[];if(!d.matchups)d.matchups={};if(!d.freeNote)d.freeNote="";setStore(d);}
function key(){return `${selectedMy}__VS__${selectedOpponent}`;}
function blankMatchup(){return {rating:"未設定",quick:"",stages:Object.fromEntries(stages.map(s=>[s.name,"□"])),details:defaultSections.map(title=>({title,text:""})),persons:[],tournaments:[],videos:[]};}
function getMatchup(){const d=getStore();return d.matchups[key()]||blankMatchup();}function setMatchup(m){const d=getStore();d.matchups[key()]=m;setStore(d);}
function esc(v){return String(v||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));}
function token(name){const map={"マリオ":"M","ドンキーコング":"DK","リンク":"L","サムス/ダークサムス":"S/D","ヨッシー":"Y","カービィ":"K","フォックス":"Fx","ピカチュウ":"Pk","ルイージ":"Lu","ネス":"Ns","キャプテン・ファルコン":"CF","プリン":"Pr","ピーチ/デイジー":"P/D","ピット/ブラックピット":"P/B","シモン/リヒター":"S/R","ホムラ/ヒカリ":"H/H","ポケモントレーナー":"PT","ベレト/ベレス":"B/B","スティーブ":"St","クラウド":"Cl","ソラ":"So","カズヤ":"Ka"};return map[name]||name.replace("Mr.ゲーム&ウォッチ","GW").replace("ゼロスーツサムス","ZSS").slice(0,3);}
function nameToFile(name){return name.replace(/[&/・\.\s]/g,"_").replace(/[（）()]/g,"");}
function iconHtml(name,cls="card"){const file=charIconMap[name]||nameToFile(name)+".png";const fb=token(name);return `<div class="char-icon ${cls}" data-fallback="${fb}"><img src="images/${file}" alt="${name}" onerror="this.remove();this.parentElement.textContent=this.parentElement.dataset.fallback;"></div>`;}
function ratingShort(r){return r&&r!=="未設定"?r.split(" ")[0]:"";}
function renderHome(){const d=getStore();$("freeNote").value=d.freeNote||"";const list=$("registeredList");list.innerHTML="";if(!d.registered.length){list.innerHTML="<p class='hint'>まだ登録キャラがありません。</p>";return;}d.registered.forEach(name=>{const card=document.createElement("button");card.className="registered-card";card.innerHTML=`${iconHtml(name,"card")}<div class="registered-name">${name}</div>`;card.onclick=()=>{selectedMy=name;$("selectedMyIcon").innerHTML=iconHtml(name,"big");$("selectedMyName").textContent=name;$("opponentSearch").value="";renderOpponentGrid();show("opponentScreen");};list.appendChild(card);});}
function renderRegisterGrid(){const d=getStore(),q=$("registerSearch").value.trim().toLowerCase(),grid=$("registerGrid");grid.innerHTML="";characters.filter(n=>n.toLowerCase().includes(q)).forEach(name=>{const btn=document.createElement("button"),isReg=d.registered.includes(name);btn.className="character-card"+(isReg?" registered":"");btn.innerHTML=`${iconHtml(name)}<div class="char-name">${name}</div>`;btn.onclick=()=>{const data=getStore();if(data.registered.includes(name))data.registered=data.registered.filter(n=>n!==name);else data.registered.push(name);setStore(data);renderRegisterGrid();renderHome();};grid.appendChild(btn);});}
function renderOpponentGrid(){const q=$("opponentSearch").value.trim().toLowerCase(),grid=$("opponentGrid"),d=getStore();grid.innerHTML="";characters.filter(n=>n.toLowerCase().includes(q)).forEach(name=>{const btn=document.createElement("button"),m=d.matchups[`${selectedMy}__VS__${name}`];btn.className="character-card"+(m?.rating&&m.rating!=="未設定"?" has-rating":"");if(m?.rating)btn.dataset.ratingShort=ratingShort(m.rating);btn.innerHTML=`${iconHtml(name)}<div class="char-name">${name}</div>`;btn.onclick=()=>{selectedOpponent=name;openMatchup();};grid.appendChild(btn);});}
function openMatchup(){$("heroMyIcon").innerHTML=iconHtml(selectedMy,"hero");$("heroOpponentIcon").innerHTML=iconHtml(selectedOpponent,"hero");$("heroMyName").textContent=selectedMy;$("heroOpponentName").textContent=selectedOpponent;const m=getMatchup();$("ratingSelect").value=m.rating;$("quickMemo").value=m.quick||"";renderStages();renderDetails();renderPersons();renderTournaments();renderVideos();show("matchupScreen");}
function renderStages(){const m=getMatchup(),list=$("stageList");list.innerHTML="";stages.forEach(s=>{const row=document.createElement("div");row.className="stage-row";row.innerHTML=`<div class="stage-thumb">${s.short}</div><div class="stage-name">${s.name}</div><select class="stage-select" data-stage="${s.name}"><option value="◎">◎</option><option value="○">○</option><option value="□">□</option><option value="❌">❌</option></select>`;list.appendChild(row);row.querySelector("select").value=m.stages?.[s.name]||"□";});document.querySelectorAll(".stage-select").forEach(sel=>{sel.onchange=()=>{const m=getMatchup();if(!m.stages)m.stages=Object.fromEntries(stages.map(s=>[s.name,"□"]));m.stages[sel.dataset.stage]=sel.value;setMatchup(m);};});}
function renderDetails(){const m=getMatchup();if(!m.details)m.details=defaultSections.map(title=>({title,text:""}));const list=$("detailList");list.innerHTML="";m.details.forEach((sec,i)=>{const btn=document.createElement("button");btn.className="detail-card";btn.innerHTML=`<div><div class="detail-title">${esc(sec.title)}</div><div class="detail-preview">${esc(sec.text||"タップして編集")}</div></div><div>›</div>`;btn.onclick=()=>openDetailModal(i);list.appendChild(btn);});}
function openDetailModal(i){editingSectionIndex=i;const m=getMatchup();$("modalTitle").textContent=m.details[i].title;$("modalTextarea").value=m.details[i].text||"";$("editorModal").classList.remove("hidden");}function closeModal(){$("editorModal").classList.add("hidden");editingSectionIndex=null;}
function renderPersons(){const m=getMatchup(),list=$("personList");list.innerHTML="";if(!m.persons?.length){list.innerHTML="<p class='hint'>まだ人対メモがありません。</p>";return;}m.persons.forEach(item=>{const card=document.createElement("div");card.className="item-card";card.innerHTML=`<div class="item-top"><strong>${esc(item.name)}</strong><button class="delete-btn" data-type="person" data-id="${item.id}">削除</button></div><p>${esc(item.note).replaceAll("\\n","<br>")}</p>`;list.appendChild(card);});bindDelete();}
function renderTournaments(){const m=getMatchup(),list=$("tournamentList");list.innerHTML="";if(!m.tournaments?.length){list.innerHTML="<p class='hint'>まだ大会メモがありません。</p>";return;}m.tournaments.forEach(item=>{const card=document.createElement("div");card.className="item-card";card.innerHTML=`<div class="item-top"><strong>${esc(item.event||"大会")}</strong><button class="delete-btn" data-type="tournament" data-id="${item.id}">削除</button></div><p>${esc(item.date||"")} / ${esc(item.round||"")} / ${esc(item.opponent||"")} / ${esc(item.result||"")}</p><p>${esc(item.note).replaceAll("\\n","<br>")}</p>`;list.appendChild(card);});bindDelete();}
function renderVideos(){const m=getMatchup(),list=$("videoList");list.innerHTML="";if(!m.videos?.length){list.innerHTML="<p class='hint'>まだ動画メモがありません。</p>";return;}m.videos.forEach(item=>{const url=esc(item.url),card=document.createElement("div");card.className="item-card";card.innerHTML=`<div class="item-top"><strong>${esc(item.title||"動画")}</strong><button class="delete-btn" data-type="video" data-id="${item.id}">削除</button></div><p><a href="${url}" target="_blank" rel="noopener noreferrer">${url}</a></p><p>${esc(item.note).replaceAll("\\n","<br>")}</p>`;list.appendChild(card);});bindDelete();}
function bindDelete(){document.querySelectorAll(".delete-btn").forEach(btn=>btn.onclick=()=>{const m=getMatchup(),type=btn.dataset.type,id=Number(btn.dataset.id);if(type==="person")m.persons=m.persons.filter(x=>x.id!==id);if(type==="tournament")m.tournaments=m.tournaments.filter(x=>x.id!==id);if(type==="video")m.videos=m.videos.filter(x=>x.id!==id);setMatchup(m);renderPersons();renderTournaments();renderVideos();});}
$("openRegisterBtn").onclick=()=>{renderRegisterGrid();show("registerScreen");};$("backHomeFromRegister").onclick=()=>{renderHome();show("homeScreen");};$("backHomeFromOpponent").onclick=()=>{renderHome();show("homeScreen");};$("backOpponentBtn").onclick=()=>{renderOpponentGrid();show("opponentScreen");};$("registerSearch").oninput=renderRegisterGrid;$("opponentSearch").oninput=renderOpponentGrid;$("saveFreeNoteBtn").onclick=()=>{const d=getStore();d.freeNote=$("freeNote").value;setStore(d);alert("保存しました");};$("ratingSelect").onchange=()=>{const m=getMatchup();m.rating=$("ratingSelect").value;setMatchup(m);};$("saveQuickBtn").onclick=()=>{const m=getMatchup();m.quick=$("quickMemo").value;m.rating=$("ratingSelect").value;setMatchup(m);alert("保存しました");};
document.querySelectorAll(".tab").forEach(tab=>{tab.onclick=()=>{document.querySelectorAll(".tab").forEach(t=>t.classList.remove("active"));document.querySelectorAll(".tab-content").forEach(c=>c.classList.remove("active"));tab.classList.add("active");$("tab"+tab.dataset.tab[0].toUpperCase()+tab.dataset.tab.slice(1)).classList.add("active");};});
$("addDetailSectionBtn").onclick=()=>{const title=prompt("追加する項目名");if(!title)return;const m=getMatchup();if(!m.details)m.details=[];m.details.push({title,text:""});setMatchup(m);renderDetails();};$("closeModalBtn").onclick=closeModal;$("saveSectionBtn").onclick=()=>{const m=getMatchup();m.details[editingSectionIndex].text=$("modalTextarea").value;setMatchup(m);closeModal();renderDetails();};$("deleteSectionBtn").onclick=()=>{if(!confirm("この項目を削除しますか？"))return;const m=getMatchup();m.details.splice(editingSectionIndex,1);setMatchup(m);closeModal();renderDetails();};
$("addPersonBtn").onclick=()=>{if(!$("personName").value.trim()&&!$("personNote").value.trim())return;const m=getMatchup();if(!m.persons)m.persons=[];m.persons.unshift({id:Date.now(),name:$("personName").value,note:$("personNote").value});setMatchup(m);$("personName").value="";$("personNote").value="";renderPersons();};
$("addTournamentBtn").onclick=()=>{const m=getMatchup();if(!m.tournaments)m.tournaments=[];const myScore=$("myScore")?.value||"";const opponentScore=$("opponentScore")?.value||"";const score=(myScore!==""||opponentScore!=="")?`${myScore||0}-${opponentScore||0}`:"";const result=(($("winLose")?.value||"")+ (score?(" "+score):"")).trim();m.tournaments.unshift({id:Date.now(),event:$("eventName").value,round:$("roundName").value,opponent:$("tournamentOpponent").value,result:result,date:$("eventDate").value,note:$("eventNote").value});setMatchup(m);["eventName","roundName","tournamentOpponent","eventDate","eventNote"].forEach(id=>$(id).value="");if($("winLose"))$("winLose").value="勝ち";if($("myScore"))$("myScore").value="";if($("opponentScore"))$("opponentScore").value="";renderTournaments();};
$("addVideoBtn").onclick=()=>{const m=getMatchup();if(!m.videos)m.videos=[];m.videos.unshift({id:Date.now(),title:$("videoTitle").value,url:$("videoUrl").value,note:$("videoNote").value});setMatchup(m);["videoTitle","videoUrl","videoNote"].forEach(id=>$(id).value="");renderVideos();};
initStore();renderHome();
